### ISSUE TITLE
Cell background color

### ISSUE THREAD

**Issue by llike** [litixsoft/lx-pdf#12]
Hello,
Is there possibility to set cell bg color (not full table)?

**Comment by LitixThomas** [comment]
Not at the moment. However, is on the TODO list. :)

**Comment by seb-esperanto** [comment]
+1 !
:)

**Comment by LitixThomas** [comment]
I'll have a look. :)

**Comment by LitixThomas** [comment]
With the currently used PDF Kit version this can not be implemented. It would have to be change too much, but I have no time at the moment.
