### ISSUE TITLE
later, browser compatible versions of pdfkit

### ISSUE THREAD

**Issue by robertknecht** [litixsoft/lx-pdf#15]
Can you update the package.json to take later versions of pdfkit, like 0.7.1? I'm trying to use lx-pdf to generate reports from a browser, and browserify is generating an error when using pdfkit 0.2.7.

**Comment by LitixThomas** [comment]
This is unfortunately not so simple. I think lx-PDF needs a redesign to work with newer PDFKit versions. But, at the moment, I have no time to do that.

Maybe in a future release. Far Far away. :)

**Comment by robertknecht** [comment]
Thanks, Thomas, for the quick responses! I plugged in 0.7.1 for my project, and I'm going to see if I run into any snags for my purposes. I'll post here if I run into anything interesting.
