### ISSUE TITLE
TypeError: filestream.readFileSync is not a function

### ISSUE THREAD

**Issue by rajeshwar-fissionhq** [litixsoft/lx-pdf#18]
I am using `webpack` in my `vue js` web application. And this is the fs setup i have in webpack.base.conf.js file
```
node: {
  fs: 'empty',
},
```

Why is this error coming?

Error while using this plugin.
![screen shot 2017-04-05 at 5 22 16 pm](https://cloud.githubusercontent.com/assets/11268935/24704260/7b04fea0-1a24-11e7-8b9c-394ac6fe0c47.png)

**Comment by LitixThomas** [comment]
Hi,

lx-pdf it's a Node.js module. I do not think so that's compatible with webpack.
