### ISSUE TITLE
WARNING: Section "content" not found

### ISSUE THREAD

**Issue by brenthmiras** [litixsoft/lx-pdf#2]
When i run the example code:

var lxDocument = require('lx-pdf.js')('template.json');
 
// Add text to Document section 'content' 
var text = '<some text>';
lxDocument.addContent('content', text);
 
// Add more text another stuff to document 
...
 
// Save document to local storage 
lxDocument.save('document.pdf', function(result) {
  // If result NULL then success otherwise it hold error informationen 
});

It doesnt work. I print the error it says WARNING: Section "content" not found.
I put my template.json in the same directory and it looks like this:

{
    // "fonts": { ... }, // Font templates
    // "header": { // see Page Header and Footer
    //     "font": { ... },
    //     "format": { ... },
    //     "data": [ ... ]
    // },
    // "footer": { // see Page Header and Footer
    //     "font": { ... },
    //     "format": { ... },
    //     "data": [ ... ]
    // },
    "options": {
        "pages": [ // Page setup
            {
                "layout": {
                    "size": "A4", // DIN Format
                    "header": false, // Turns OFF defined header area, default is turned on
                    "footer": false, // Turns OFF defined footer area, default is turned on
                    "layout": "portrait", // Orientation portait|landscape
                    "margins": {
                        "top": 0,
                        "left": 0,
                        "bottom": 0,
                        "right": 0
                    }
                },
                
                "sections": {
                        "content": { // Sectionname
                            "text": "",  // Default text or table object. There will be always showed.
                            "font": "body", // Defined font template name, or font object
                            "format": {
                                "align": "justify", // left|right|justify
                                "left": 70,
                                "top": 670,
                                "width": 481,
                                "height": 70
                            }
                        }
                }
            }
        ]
    }
}

**Comment by LitixThomas** [comment]
Your template does not match the JSON standard. The comments and the placeholders must be removed. In the test directory, check templates also two working examples.

working solution:

```javascript
var lxDocument = require('lx-pdf')('template.json');

// Add text to Document section 'content'
var text = '<some text>';
lxDocument.addContent('content', text);

// Save document to local storage
lxDocument.save('document.pdf', function(result) {
    // If result NULL then success otherwise it hold error informationen
});
```

```
{
  "options": {
    "pages": [
      {
        "layout": {
          "size": "A4",
          "header": false,
          "footer": false,
          "layout": "portrait",
          "margins": {
            "top": 0,
            "left": 0,
            "bottom": 0,
            "right": 0
          }
        },
        "sections": {
          "content": {
            "text": "",
            "font": "body",
            "format": {
              "align": "justify",
              "left": 70,
              "top": 670,
              "width": 481,
              "height": 70
            }
          }
        }
      }
    ]
  }
}
```

**Comment by arjun30** [comment]
Getting WARNING: Section "title" not found. 


{
  "name": "Dummy Template for public",
  "version": "1.0.0",
  "debug": false,
  "header": {
    "font": {
      "name": "./public/fonts/arial.ttf",
      "size": 8,
      "color": "#808080"
    },
    "format": {
      "align": "center",
      "height": 20
    },
    "data": ""
  },
  "footer": {
    "font": {
      "name": "./public/fonts/arial.ttf",
      "size": 6,
      "color": "#808080"
    },
    "format": {
      "align": "center",
      "height": 30,
      "textmargin": {
        "left": 10,
        "right": 10
      },
      "background": "#000000"
    },
    "data": ""
  },
  "options": {
    "pages": [
      {
        "layout": {
          "size": "A4",
          "layout": "portrait",
          "header": false,
          "footer": false,
          "margins": {
            "top": 0,
            "left": 0,
            "bottom": 0,
            "right": 0
          }
        },
        "sections": {
          "heading": {
            "font": {
              "name": "./public/fonts/arial.ttf",
              "size": 22,
              "color": "#000000"
            },
            "format": {
              "align": "center",
              "left": 70,
              "top": 250,
              "width": 481,
              "height": 320
            }
          },
          "logo": {
            "format": {
              "align": "justify",
              "top": 20,
              "left": 150,
              "width": 100,
              "height": 100
            }
          }
        }
      },
      {
        "layout": {
          "size": "A4",
          "layout": "portrait",
          "header": false,
          "footer": false,
          "margins": {
            "top": 0,
            "left": 0,
            "bottom": 0,
            "right": 0
          }
        },
        "sections": {
          "content": {
            "font": "default",
            "format": {
              "align": "justify",
              "left": 70,
              "top": 20,
              "width": 741,
              "height": 50
            }
          },
          "title": {
            "font": {
              "name": "./public/fonts/arialbd.ttf",
              "size": 11,
              "color": "#000000"
            },
            "format": {
              "align": "justify",
              "left": 20,
              "top": 40,
              "width": 600,
              "height": 450
            }
          }
        }
      }
    ]
  }
}


app.get('/getlxpdf', function(req, res) {


	//Use the below to send file and promt user to save it to disk
	 //lxpdf.loadTemplate('./public/templates/template.json');

	lxpdf.showTextboxframe(false);
	lxpdf.addContent('heading', 'STATEMENT OF WORKS \n FOR \n DOGFI.SH');
	lxpdf.addImage('logo', 'public/images/litixlogo.png');

    lxpdf.addPageBreak();

    

        var tableHeader1 = [
            {text: 'Quantity 1', width: 120, align: 'center', font: {name: './public/fonts/arial.ttf', size: 12, color: '#000000', border: {
                        color: '#ff0000',
                        style: 'normal',
                        position: ['bottom', 'top','left','right'],
                        linemode: true,
                        linewidth: 1
                    }}},
            {text: 'Description of Goods, Services',width: 150, align: 'center', font: {name: './public/fonts/arial.ttf', size: 12, color: '#000000'}},
            {text: 'Unit Price', width: 80,align: 'center', font: {name: './public/fonts/arial.ttf', size: 12, color: '#000000'}},
            {text: 'Total (not including VAT)', width: 180, align: 'center', font: {name: './public/fonts/arial.ttf', size: 12, color: '#000000'}}
        ];

        var tableData1 = [
            // Simple Row
            [{
                    text: ' Nike Dogfi.sh 5Msl',

                    border: {
                        color: '#ff0000',
                        backgroundColor:'#c0c0c0',
                        style: 'normal',
                        position: ['bottom', 'top','left','right'],
                        linemode: true,
                        linewidth: 1
                    }
                }, 'Cell B1', 'Cell C1', 'Cell D1'],
                [{
                    text: ' Nike 5Msl',

                    border: {
                        color: '#ff0000',
                        backgroundColor:'#c0c0c0',
                        style: 'normal',
                        position: ['bottom', 'top','left','right'],
                        linemode: true,
                        linewidth: 1
                    }
                }, 'Cell B1', 'Cell C1', 'Cell D1'],
                [{
                    text: ' Puma 5Msl',

                    border: {
                        color: '#ff0000',
                        backgroundColor:'#c0c0c0',
                        style: 'normal',
                        position: ['bottom', 'top','left','right'],
                        linemode: true,
                        linewidth: 1
                    }
                }, 'Cell B1', 'Cell C1', 'Cell D1'],
                [{
                    text: ' Adidas 5Msl',

                    border: {
                        color: '#ff0000',
                        backgroundColor:'#c0c0c0',
                        style: 'normal',
                        position: ['bottom', 'top','left','right'],
                        linemode: true,
                        linewidth: 1
                    }
                }, 'Cell B1', 'Cell C1', 'Cell D1']
 
        ];

        lxpdf.showTextboxframe(false);
        lxpdf.addContent('content', 'Report for year 2014');
        lxpdf.addTable('title', tableData1, tableHeader1);



        //lxpdf.addContent('content', '\nLorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.');    


        //lxpdf.addContent('content1', '\nLorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.');    

		lxpdf.save('public/testdoc.pdf', function (error) {
		//expect(result).toBeNull();
		console.log('entered'+JSON.stringify(error));
		res.send(200);
		
        });
});

**Comment by LitixThomas** [comment]
This is really a mistake. I'll fix this asap.

**Comment by arjun30** [comment]
In second page section ,if there are more then one element in section it takes valid page number during adding inside document but for second element it takes 0 as pageindex.

Temp fix:
 lxpdf.addContent('content', 'Report for year 2014');
 lxpdf.addTable('title', tableData1, tableHeader1,1(page index)) ;//pass page index

**Comment by LitixThomas** [comment]
Your fix shall work, but is only a workaround. :) I have updated the version on github and npm. Please check it out.

**Comment by arjun30** [comment]
Thanks LitixThomas. It's working now  :)

**Comment by LitixThomas** [comment]
You're welcome!
