### ISSUE TITLE
No options and top position in addImage function

### ISSUE THREAD

**Issue by sshhawwnn** [litixsoft/lx-pdf#5]
I have modified line 1015 in my own copy of lx-pdf.js:
```
                    } else if (entry.image) {
                        var imageHeight = currentPDFDocument.y,
                            sectionDimension = getSectionDimension(sectionName),
                            options = entry.image.options;

                        imageHeight = currentPDFDocument.image(entry.image.filename, sectionDimension.left || 0, sectionDimension.top || 0, { width: options.width }).y - imageHeight;
                        sectionInfo.topIndex += imageHeight;
                    }
```

My new functionality.
doc.addImage(sectionName, image, { width: xxx });

Please update the codes. Thanks.

**Comment by LitixThomas** [comment]
I'll look like I can add your suggestion. The current functionality appends the image automatically on the already added content. See example file "dummy.pdf" when run "grunt test".

**Comment by LitixThomas** [comment]
lx-pdf was updated with new functionality to add images. Be invited to test.
